Add a passing 'build' test

diff --git a/decompose-functions b/decompose-functions
--- a/decompose-functions
+++ b/decompose-functions
@@ -125,7 +125,7 @@ decompose-init-environment() {
 
   # Copy environment files
   mkdir "$project_root/.decompose/environment"
-  local decompose_data_dir=$(realpath ~/.local/share/decompose)
+  local decompose_data_dir; decompose-global-data-dir decompose_data_dir
   local environment_hash
   decompose-md5-hash $environment_url environment_hash
   cp -r "$decompose_data_dir/ecosphere/$environment_hash/"* "$project_root/.decompose/environment"
@@ -200,14 +200,14 @@ decompose-post-process-elements() {
 decompose-update-git-repository() {
   local git_repo_url=$1
 
-  local decompose_data_dir=$(realpath ~/.local/share/decompose)
+  local decompose_data_dir; decompose-global-data-dir decompose_data_dir
 
   local git_repo_hash
   decompose-md5-hash $git_repo_url git_repo_hash
   if [ -d "$decompose_data_dir/ecosphere/$git_repo_hash" ]; then
     git -C "$decompose_data_dir/ecosphere/$git_repo_hash" pull
   else
-    git clone $git_repo_url \
+    git clone -q $git_repo_url \
       "$decompose_data_dir/ecosphere/$git_repo_hash"
   fi
 }
@@ -239,7 +239,7 @@ decompose-update-environment() {
   decompose-update-git-repository $environment_url
 
   # Update environment
-  local decompose_data_dir=$(realpath ~/.local/share/decompose)
+  local decompose_data_dir; decompose-global-data-dir decompose_data_dir
   local decompose_directory
   _decompose-find-decompose-directory decompose_directory
   local environment_hash
@@ -289,11 +289,36 @@ decompose-bootstrap() {
     exit 1
   fi
 
-  local decompose_data_dir=$(realpath ~/.local/share/decompose)
+  local decompose_data_dir; decompose-global-data-dir decompose_data_dir
   # Create ecosphere
   if [ ! -d "$decompose_data_dir/ecosphere" ]; then
     mkdir -p "$decompose_data_dir/ecosphere"
   fi
+}
+
+# Return the decompose global data directory
+# Will create the directory if it doesn't exist
+#
+# Parameters
+#   $1: return value (global data directory)
+decompose-global-data-dir() {
+  local __return_value=$1
+  local _data_directory="$HOME/.local/share/decompose"
+
+  if [ ! -d "$_data_directory" ]; then
+    echo "Creating global data directory: '$_data_directory'"
+    mkdir -p "$_data_directory"
+  fi
+  eval "$__return_value=$_data_directory"
+}
+
+# Return 1 if the function name passed in exists
+#
+# Parameters
+#   $1: function name to check
+decompose_function_exists() {
+    declare -f -F $1 > /dev/null
+    return $?
 }
 
 # Print dependencies that are missing
diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -43,18 +43,130 @@ _decompose-test-help-test() {
   return 0
 }
 
+# Building test
+_decompose-test-building-test() {
+  # Make and set home directory
+  mkdir "./tests-workspace/user-home"
+  local HOME=$(realpath "./tests-workspace/user-home")
+
+  # Set current working directory
+  working_dir="./tests-workspace/build-test"
+  mkdir "./tests-workspace/build-test"
+
+  # Setup git repository
+  git config --global user.email "tester@example.com"
+  git config --global user.name "tester"
+  git -C "./tests-workspace/build-test-environment" init >/dev/null
+  git -C "./tests-workspace/build-test-environment" add .
+  git -C "./tests-workspace/build-test-environment" commit -m "Initial commit" >/dev/null
+
+  # Init build test enviornment
+  local error_output=$(export HOME=$HOME && cd $working_dir && \
+    decompose --init "../build-test-environment" 2>&1 1>/dev/null)
+  if [ -n "$error_output" ]; then
+    echo "'decompose --init' had errors"
+    echo "$error_output"
+    return 1
+  fi
+
+  # Run Build
+  local error_output=$(export HOME=$HOME && cd $working_dir && \
+    decompose --build 2>&1 1>/dev/null)
+  if [ -n "$error_output" ]; then
+    echo "'decompose --build' had errors"
+    echo "$error_output"
+    return 1
+  fi
+
+  # Verify that the build work
+  if [ ! -e "$working_dir/testing" ]; then
+    echo "Build failed to produce '$working_dir/testing' file"
+    return 1
+  fi
+
+  return 0
+}
+_decompose-test-building-test-cleanup() {
+  # Home directory
+  local HOME="$(realpath ./tests-workspace/user-home)"
+
+  # Cleanup global data
+  $(cd $HOME; mv .local /tmp/$(uuidgen))
+
+  # Cleanup environment data
+  mv "tests-workspace/build-test" "/tmp/$(uuidgen)"
+
+  # Cleanup git repository
+  mv "./tests-workspace/build-test-environment/.git" "/tmp/$(uuidgen)"
+
+  # Cleanup home .gitconfig
+  rm "$HOME/.gitconfig"
+  rmdir "$HOME"
+}
+
+# Global data directory creation and location
+_decompose-test-global-data-directory() {
+  # Set home to 'user-home'
+  mkdir "./tests-workspace/user-home"
+  local HOME="$(realpath ./tests-workspace/user-home)"
+
+  # Verify that the global directory does not exist
+  local expected_global_dir="$HOME/.local/share/decompose"
+  if [ -d "$expected_global_dir" ]; then
+    echo "The global data directory already exists: "
+    echo "  '$expected_global_dir'"
+    return 1
+  fi
+
+  # Call function to get the directory
+  local data_directory; decompose-global-data-dir data_directory >/dev/null
+
+  # Verify the directory received is the same as expected
+  if [ "$expected_global_dir" != "$data_directory" ]; then
+    echo "The returned global directory was not what was expected."
+    echo "Expected: '$expected_global_dir'"
+    echo "Returned: '$data_directory'"
+    return 1
+  fi
+
+  # Verify that the directory exists
+  if [ ! -d "$data_directory" ]; then
+    echo "The global data directory was not created."
+    echo "  '$data_directory'"
+    return 1
+  fi
+
+  return 0
+}
+_decompose-test-global-data-directory-cleanup() {
+  # Cleanup the directory that was created
+  local HOME="$(realpath ./tests-workspace/user-home)"
+  $(cd $HOME; rmdir -p .local/share/decompose)
+
+  # Remove user-home
+  rmdir "./tests-workspace/user-home"
+}
+
+
 _decompose-test-run-tests() {
-  local _decompose_tests_to_run=( 'no-stderr' 'help-test' )
+  local _decompose_tests_to_run=( 'no-stderr' 'help-test' 'building-test'
+    'global-data-directory' )
   
   for test in ${_decompose_tests_to_run[@]}; do
+    # Run test
     _decompose-test-$test
-    error_code="$?"
+    local error_code="$?"
+
+    # Cleanup test
+    decompose_function_exists "_decompose-test-$test-cleanup" && \
+      _decompose-test-$test-cleanup
     
+    # Report results
     echo -n "Test '$test': "
     if [ "$error_code" -gt "0" ]; then
       echo "FAIL with return code '$error_code'"
     else
-      echo "PASS" 
+      echo "PASS"
     fi
   done
 }
