Add ignore build files tests with passing functionality

diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -147,10 +147,32 @@ _decompose-test-global-data-directory-cleanup() {
   rmdir "./tests-workspace/user-home"
 }
 
+_decompose-test-build-ignores() {
+  # Build environment
+  _decompose-test-building-test
+  local error_code="$?"
+  if [ "$error_code" -gt "0" ]; then
+    echo "Build failed"
+    return 1
+  fi
+
+  # Verify that the ignore directory wasn't processed
+  if [ -e "./tests-workspace/build-test/ignore_me/a_file" ]; then
+    echo "'a_file' was generated when it should have been ignored"
+    return 1
+  fi
+
+  return 0
+}
+_decompose-test-build-ignores-cleanup() {
+  # Cleanup
+  _decompose-test-building-test-cleanup
+}
+
 
 _decompose-test-run-tests() {
   local _decompose_tests_to_run=( 'no-stderr' 'help-test' 'building-test'
-    'global-data-directory' )
+    'global-data-directory' 'build-ignores' )
   
   for test in ${_decompose_tests_to_run[@]}; do
     # Run test
